# Generated by Django 4.0.3 on 2022-04-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=200)),
                ('OwnsRouter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200)),
                ('AmmountOfItem', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.customers')),
            ],
        ),
    ]
