# Generated by Django 4.0.3 on 2022-04-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('DeliveryCost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('DeliveryLength', models.IntegerField()),
                ('Type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('VenderID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WishListTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Hertz', models.IntegerField()),
                ('ScreenType', models.CharField(max_length=200)),
                ('ScreenSize', models.IntegerField()),
                ('PriorityList', models.IntegerField()),
                ('WishID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.customerwishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishListPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Quality', models.CharField(max_length=200)),
                ('Generation', models.IntegerField()),
                ('CameraQuality', models.IntegerField()),
                ('PriorityList', models.IntegerField()),
                ('WishID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.customerwishlist')),
            ],
        ),
        migrations.CreateModel(
            name='TVs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Hertz', models.IntegerField()),
                ('ScreenType', models.CharField(max_length=200)),
                ('ScreenSize', models.IntegerField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.products')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('SubscriptionPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SubscriptionLength', models.IntegerField()),
                ('ContractLength', models.IntegerField()),
                ('VenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.vender')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='VenderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.vender'),
        ),
        migrations.CreateModel(
            name='PhoneServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataCap', models.IntegerField()),
                ('HotSpot', models.BooleanField()),
                ('Speed', models.IntegerField()),
                ('ServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.service')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Quality', models.CharField(max_length=200)),
                ('Generation', models.IntegerField()),
                ('CameraQuality', models.IntegerField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.products')),
            ],
        ),
        migrations.CreateModel(
            name='InternetServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speed', models.IntegerField()),
                ('DataCap', models.IntegerField()),
                ('IncludesRouter', models.BooleanField()),
                ('ServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStore.service')),
            ],
        ),
    ]
