# Generated by Django 4.0.3 on 2022-05-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebStore', '0002_products_vender_wishlisttv_wishlistphone_tvs_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='OwnsRouter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerwishlist',
            name='AmmountOfItem',
            field=models.IntegerField(default=1),
        ),
    ]
